sudo: required
services:
  - docker

before_install:
  - docker build -t stuartlogan82/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stuartlogan82/react-test npm test

after_success:
  - docker build -t stuartlogan82/multi-client ./client
  - docker build -t stuartlogan82/multi-nginx ./nginx
  - docker build -t stuartlogan82/multi-server ./server
  - docker build -t stuartlogan82/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Psuh images to docker hub
  - docker push stuartlogan82/multi-client
  - docker push stuartlogan82/multi-nginx
  - docker push stuartlogan82/multi-server
  - docker push stuartlogan82/multi-worker
